### ISSUE TITLE
HTTP 404 when running app/target/app.jar as in the tutorial

### ISSUE THREAD

**Issue by YpeKingma** [osgi/osgi.enroute#63] opened 2018-06-21 19:03 UTC
At this page in the tutorial the problem below occurs:
 https://enroute.osgi.org/tutorial/020-tutorial_qs.html

I'm using ubuntu 18.10, oracle java 10.0.1 and mvn 3.5.3.
I cloned the osgi.enroute repo today, it is at master 2497da546.

The mvn verify step went well, it took just over 2 minutes here.

Then  java -jar app/target/app.jar also appeared to go well,
but the http://localhost:8080/quickstart/index.html
page showed an HTTP 404 when running the target app.

So I restarted to get a log:
java -jar app/target/app.jar >& log.txt
which gave this log.txt when the 404 happens:
[log.txt](https://github.com/osgi/osgi.enroute/files/2124945/log.txt)

Early in the log there is this, it could be the root cause, but I'm only starting with OSGi:

! Failed to start bundle org.apache.aries.javax.jax.rs-api-0.0.1.201806180958, exception Unable to resolve org.apache.aries.javax.jax.rs-
api [4](R 4.0): missing requirement [org.apache.aries.javax.jax.rs-api [4](R 4.0)] osgi.wiring.package; (osgi.wiring.package=javax.xml.bind.annotation) Unresolved requirements: [[org.apache.aries.javax.jax.rs-api [4](R 4.0)] osgi.wiring.package; (osgi.wiring.package=javax.xml.bind.annotation)]

Minor point:
I installed bndtools 4.0.0.REL in eclipse 4.7.3a from the eclipse marketplace,
but I don't think I have used them yet for the tutorial.
The tutorial here https://enroute.osgi.org/tutorial/015-Prerequisite.html
says that bndtools is not yet available in the eclipse marketplace, this has probably changed recently.

**Comment by timothyjward** [comment] 2018-06-21 19:16
The enRoute examples target Java 8 (the current long term support release of Java). You can see a discussion of why you get this failure [in this issue](https://github.com/osgi/osgi.enroute/issues/47#issuecomment-382637635)

If you use Java 8 it will be fine, otherwise you need to start Java 10 including the JAXB annotations on the root classpath, or you need to re-resolve with Java 10 as the target platform with a JAXB API jar in your repository. 

They really did a number on API backward compatibility in Java 9...

**Comment by timothyjward** [comment] 2018-06-21 19:17
Closed as a duplicate of #47

**Closed by timothyjward** 2018-06-21 19:16 UTC
